name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  google_maps: ">=3.0.0 <4.0.0"

#  google_maps: ^3.4.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.4+8
  #  geo locator
  markdown:
  geolocator: ^5.3.2+2
#  geocoding: ^1.0.4
  url_launcher: ^5.5.0
  flutter_typeahead: ^1.8.7
#  firebase_messaging: ^7.0.0
  flutter_local_notifications: ^0.7.1+1
  fluttertoast: ^3.0.4
  autocomplete_textfield: ^1.6.4
#  location: ^3.2.4
  audioplayers: ^0.16.1
  flutter_audio_recorder: ^0.5.5
#  simple_tooltip: ^0.1.14
  permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+12
  simple_autocomplete_formfield: ^0.2.7
#  autocomplete_textfield: ^1.7.3
  razorpay_flutter: ^1.2.2
  dio:
  image_picker: ^0.6.7+4
  barcode_scan: any
#  qr_code_scanner:
  device_info: ^0.4.0+4
#  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.0.13
#  flutter_datetime_picker: ^1.4.0
  image_gallery_saver: ^1.5.0
  progress_dialog:
  toast: ^0.1.5
  flutter_map:
  location_permissions: ^3.0.0
  path_provider:
  intl:
  connectivity: ^0.4.8+2
  flutter_speed_dial: ^1.0.9
  carousel_pro: ^1.0.0
  ping_discover_network: ^0.2.0+1
  printing:
  image:
  esc_pos_printer:
  esc_pos_bluetooth:
  charset_converter:
  webview_flutter:
  flutter_html_to_pdf:
  flutter_pdfview:
  google_fonts:
#  flutter_inappwebview:
  data_tables:
  sqflite: ^1.3.2+4







dev_dependencies:
  flutter_test:
    sdk: flutter


  http: ^0.12.0+4
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  image_path: "assets/icon1.jpg"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/my_file.txt
    - assets/
    - assets/beep.mp3
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Arial
      fonts:
        - asset: assets/arial.ttf
        - asset: assets/FontsFree-Net-arial-bold.ttf
#        - asset: assets/arial_Bold.ttf
#          weight: 700

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
